Update basescope.md
LUMC-BioSemantics/bind pull request #4
Opened 2023-03-17 11:24 UTC by PPerdomoQ

Dear @NuriaQueralt I've created this brach to review the changes of WP2 Basescope. I've updated the basescope.md and will now upload the image.

2023-03-22 09:47 UTC, NuriaQueralt requested changes
Hi @PPerdomoQ Please review: labels; that all entities have at least one term described in OBO and SIO; I would suggest to use as relationship between dmd gene and dystrophin isoform sio:is-encoded-by since it is more specific; I cannot see how 'protocol' is connected in the model. Thanks!

2023-03-27 15:15 UTC, NuriaQueralt commented
Hi @PPerdomoQ thank you very much. I see that you did a lot of commits to different files. Could you point me at the actual files that you want me to have a look at it?

2023-03-29 08:34 UTC, PPerdomoQ commented
Hi @NuriaQueralt! My bad... I messed up a bit while doing the changes... By checking the .md files (basescope, single-cell and phenotype) and the .png files (in the folder images/rdf of each WP) you should be able to see all the changes.

2023-04-06 18:23 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/docs/basescope.md
>  :person_ a sio:SIO_000498 ;
Hi @PPerdomoQ could you add the obo class to person? Thanks

2023-04-06 18:29 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/docs/basescope.md
>  :protocol_ a sio:SIO_001043, obo:NCIT_C143028 ;
To what does protocol link to or is linked to?

2023-04-06 18:32 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/docs/basescope.md
>  :dp_detection_ a sio:SIO_000015, obo:NCIT_C15783 ;
typo

2023-04-06 18:33 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/docs/basescope.md
>      rdfs:label "Outout: Dystrophin Isoform Detection"^^xsd:string ;
typo

2023-04-06 18:57 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/docs/basescope.md
> +:isoform_ a obo:NCIT_C47803;
Could you add sio:isoform (SIO_001445) type? SIO developers kindly attended our request and minted&added it in the ontology :)

2023-04-06 19:01 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/docs/basescope.md
> +    sio:SIO_000300 "Dp140"^^xsd:string ;
Note for ourselves: This triple is good for now. We should modify it if there is an ontological term/standard vocabulary for mouse isoforms (we should ask to domain experts).

2023-04-06 19:31 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/docs/basescope.md
>  :rna_process_ a obo:OBI_0001177, sio:SIO_000006 ;
Is this term more appropriate http://purl.obolibrary.org/obo/OBI_0002575? If not I would suggest then this http://purl.obolibrary.org/obo/OBI_0001271, which is a subclass of the current one.

2023-04-06 19:35 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/docs/basescope.md
> +    sio:SIO_000300 "Yes/No"^^xsd:string .
It is strange to me that the output of a sequencing assay is a string of values "yes/no". I would suggest to keep the real data here, i.e., 1/0 integers

2023-04-06 20:12 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/docs/basescope.md
>      rdfs:label "Role: Patient"^^xsd:string ;
Could you change the label to the new one, which is post mortem donor?

2023-04-06 20:21 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/docs/basescope.md
I would suggest to use only SIO properties. The reason why is that EJP RD CDE modelling adopts a SIO design pattern, which means that the pattern is defined by classes and properties from SIO. Please, could you look for alternatives to HSO and ERO properties?

2023-04-06 20:41 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/docs/basescope.md
> +:isoform_ a obo:NCIT_C47803, sio:SIO_010043, obo:PR_P11532-12;
I suggest to keep only one OBO class, so I suggest to remove the more general one, which is NCIT

2023-04-06 21:02 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/images/rdf/basescope.png
Perfect!

2023-04-13 15:28 UTC, NuriaQueralt commented on fair-data-models/phenotype-wp3/docs/phenotype.md
>      sio:SIO_000008 :age_.
Dear @PPerdomoQ could you double check that all entities have at least one OBO and one SIO class? at least in the version file I am seeing, :identifier_ only has one class (SIO) type. But I could be looking at the not most up-to-date version of the file where you have already solve it. So, forget it if this is the case :)

Also, for mouse in WP4 I have a different semantic description: 
:mouse_ a obo:NCBITaxon_10090, sio:SIO_010375 ;

we should be consistent. We agreed to use OBO NCBITaxon, but for SIO I have multicellular organism and you have mouse. As agreed, I chose a SIO concept that is more genereral and allows to retrieve both human and mouse. Do you agree with changing your semantics to be consistent with mine?

2023-04-14 10:13 UTC, NuriaQueralt commented on fair-data-models/phenotype-wp3/docs/phenotype.md
> +:isoform_ a obo:NCIT_C47803, sio:SIO_010043, obo:PR_P11532-12 ;
Could you remove NCIT and change SIO class to sio:isoform?

2023-04-14 12:07 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/docs/single_cell.md
>      rdfs:label "Role: Specimen"^^xsd:string ;
Could you change the label as 'control group role' or something like this according to the obi class you changed? I think 'specimen' now is confusing.

2023-04-14 12:29 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/docs/single_cell.md
> +:isoform_ a obo:NCIT_C47803, sio:SIO_010043, obo:PR_P11532-12 ;
Could you remove obo:NCIT_C47803, sio:SIO_010043 and add sio:isoform instead?

2023-04-14 14:28 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/docs/single_cell.md
> +:cell_id_ a sio:SIO_000115. obo:IAO_0020000;
Please could you replace the dot after SIO_000115 to a comma?

2023-04-14 14:32 UTC, NuriaQueralt requested changes
Dear @PPerdomoQ I reviewed your changes and proposed some changes. Could you have a look?

2023-04-17 15:40 UTC, PPerdomoQ commented on fair-data-models/rna-seq-wp2/docs/basescope.md
>      rdfs:label "Outout: Dystrophin Isoform Detection"^^xsd:string ;
I agree in that Basescope is an expression analysis, however here we are only using it for detection. I see no problem in changing it, but maybe we can consult Pietro before

2023-04-17 15:42 UTC, PPerdomoQ commented on fair-data-models/rna-seq-wp2/docs/basescope.md
> +    sio:SIO_000300 "Yes/No"^^xsd:string .
I agree. But again I would consult Pietro to see what will make more sense for researchers. Maybe we can also change it for something like 'Detected/Not Detected'?

2023-04-17 16:03 UTC, PPerdomoQ commented on fair-data-models/rna-seq-wp2/docs/basescope.md
Sorry! I didn't know they had to strinctly be SIO properties. Maybe we should discuss this in a meeting: I've search for SIO properties but I'm unsure about which one fits the best.

2023-04-19 16:43 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/docs/basescope.md
> +    sio:SIO_000300 "Yes/No"^^xsd:string .
Yes, we need Pietro's thoughts here

2023-04-19 16:43 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/docs/basescope.md
Perfect!

2023-04-21 09:16 UTC, NuriaQueralt commented on fair-data-models/phenotype-wp3/docs/phenotype.md
>  :freq_d1_ a sio:SIO_000015;
This instance needs an OBO class

2023-04-21 09:20 UTC, NuriaQueralt commented on fair-data-models/phenotype-wp3/docs/phenotype.md
> +    sio:SIO_010079 <https://identifiers.org/HGNC:2928> .
I think you should describe 'dmd gene' as a mouse gene using MGI id as in the previous version because the entity is a mouse not a human. When the entity is a human then this description with HGNC and link to the orphanet gene code is perfect. Could you change it?

2023-04-21 09:22 UTC, NuriaQueralt commented on fair-data-models/phenotype-wp3/docs/phenotype.md
Could you change the gene id to MGI id and remove the orphanet human gene class?

2023-04-21 09:34 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/docs/single_cell.md
> +:mouse_ a sio:SIO_000486, obo:NCBITaxon_10090;
Could you change the sio class to sio:SIO_010375?

2023-04-21 09:38 UTC, NuriaQueralt requested changes
Hi @PPerdomoQ I reviewed phenotype.md, basescope.md and single_cell.md files. Your changes look good. I added a few more changes suggestions.

2023-05-02 07:49 UTC, PPerdomoQ commented
Dear @NuriaQueralt , you will see that some changes have been done to the basescope file. Most of them were error fixing changes. I also added the units for the output of the process and the age

2023-05-02 10:10 UTC, PPerdomoQ commented on fair-data-models/phenotype-wp3/docs/phenotype.md
>  :freq_d1_ a sio:SIO_000015;
Done!

2023-05-02 10:10 UTC, PPerdomoQ commented on fair-data-models/phenotype-wp3/docs/phenotype.md
Done!

2023-05-02 10:10 UTC, PPerdomoQ commented on fair-data-models/rna-seq-wp2/docs/basescope.md
>      rdfs:label "Gene: Dmd"^^xsd:string .
Done!

2023-05-02 11:12 UTC, PPerdomoQ commented on fair-data-models/phenotype-wp3/docs/phenotype.md
> +    sio:SIO_010079 <https://identifiers.org/HGNC:2928> .
Done!

2023-05-02 11:16 UTC, PPerdomoQ commented
Dear @NuriaQueralt, O've finished reviewing single-cell.md :)

2023-05-02 13:06 UTC, NuriaQueralt requested changes

2023-05-02 13:06 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/docs/basescope.md
Is this fixed?

2023-05-02 13:09 UTC, NuriaQueralt requested changes

2023-05-02 13:09 UTC, NuriaQueralt commented on fair-data-models/phenotype-wp3/docs/phenotype.md
>  :freq_d1_ a sio:SIO_000015;
I cannot see how did you change it

2023-05-02 13:13 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/docs/basescope.md
>      rdfs:label "Outout: Dystrophin Isoform Detection"^^xsd:string ;
Hi @PPerdomoQ, is that fixed?

2023-05-02 13:14 UTC, NuriaQueralt commented on fair-data-models/phenotype-wp3/docs/phenotype.md
> +    sio:SIO_010079 <https://identifiers.org/HGNC:2928> .
Thank you!

2023-05-02 13:21 UTC, PPerdomoQ commented on fair-data-models/phenotype-wp3/docs/phenotype.md
>  :freq_d1_ a sio:SIO_000015;
My bad, I thought you meant obo for freezing time

2023-05-02 13:23 UTC, PPerdomoQ commented on fair-data-models/rna-seq-wp2/docs/basescope.md
>      rdfs:label "Outout: Dystrophin Isoform Detection"^^xsd:string ;
Yes! Now instead of 1/0 detection we use the true expression (float number)

2023-05-02 14:20 UTC, NuriaQueralt requested changes
Hi @PPerdomoQ I reviewed your changes in phenotype.md, single_cell.md and basescope.md files and all looks very good! I have also reviewed the ontological terms that you chose to express the semantics and you did a fanstastic job! But I have just added my last suggestions that require minor changes. I have also made a new review for your new model real-time.md, also with a couple of suggestions that require minor changes. Could you have a look?

2023-05-02 14:20 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/docs/basescope.md
> +    rdfs:label "Timestamp: Post Mortem Interval"^^xsd:string ;
I suggest removing the word 'timestamp' in the label of :postmortem_. 'Postmortem days' is an attribute of the sample. 'Days fix' is an attribute of the process. Both are temporal attributes, but I would like to associate the word 'timestamp' linked to processes following the SIO design pattern for measurements. What do you think?

2023-05-02 14:20 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/docs/basescope.md
> +    rdfs:label "Outout: Dystrophin Isoform Expression"^^xsd:string ;
Same typo in the label as before 'Outout', could you fix it?

2023-05-02 14:20 UTC, NuriaQueralt commented on fair-data-models/rna-seq-wp2/docs/real-time.md
> +    rdfs:label "Timestamp: Post Mortem Interval"^^xsd:string ;
Same comment as in basescope. I would suggest to remove 'timestamp' word in the label, and keep just for processes' temporal attribute timestamp

2023-05-02 15:02 UTC, PPerdomoQ commented on fair-data-models/rna-seq-wp2/docs/real-time.md
> +    rdfs:label "Outout: Dystrophin Isoform Expression"^^xsd:string ;
Solved!

2023-05-02 15:06 UTC, PPerdomoQ commented on fair-data-models/rna-seq-wp2/docs/basescope.md
> +    rdfs:label "Timestamp: Post Mortem Interval"^^xsd:string ;
I agree! It should be fixed now :)

2023-05-02 15:06 UTC, PPerdomoQ commented on fair-data-models/rna-seq-wp2/docs/basescope.md
> +    rdfs:label "Outout: Dystrophin Isoform Expression"^^xsd:string ;
Solved!

2023-05-02 15:06 UTC, PPerdomoQ commented on fair-data-models/rna-seq-wp2/docs/real-time.md
> +    rdfs:label "Timestamp: Post Mortem Interval"^^xsd:string ;
Solved!

2023-05-03 09:46 UTC, merged